name: Sync to yskooo/electrifai-web

on:
  push:
    branches:
      - main 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      - name: Push to Target Repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote add target https://x-access-token:${{ secrets.GH_PAT }}@github.com/yskooo/electrifai-web.git
          git push --force target main
