name: Sync to yskooo/electrifai-web

on:
  push:
    branches:
      - main  # Runs on every push to main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for accurate mirroring

      - name: Push to Target Repository (Mirror)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote add target https://x-access-token:${{ secrets.GH_PAT }}@github.com/yskooo/electrifai-web.git
          git push --mirror target  # This mirrors all changes, including force pushes and branch updates
